// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx12V7Sdsd73muCrmMW6Sq0_eQRAyZ9ic',
    appId: '1:1000135660682:web:19769433a9d912badc8973',
    messagingSenderId: '1000135660682',
    projectId: 'fruits-c4d50',
    authDomain: 'fruits-c4d50.firebaseapp.com',
    storageBucket: 'fruits-c4d50.firebasestorage.app',
    measurementId: 'G-XZTY3NEPSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkWfThfqLXVz3Ga5GyiG2KkDZ_NiS924',
    appId: '1:1000135660682:android:fa338bbb8fd91f44dc8973',
    messagingSenderId: '1000135660682',
    projectId: 'fruits-c4d50',
    storageBucket: 'fruits-c4d50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFPOb4ViHYsCSYdahBLfD44wZ0WINt3js',
    appId: '1:1000135660682:ios:e155408f22e28718dc8973',
    messagingSenderId: '1000135660682',
    projectId: 'fruits-c4d50',
    storageBucket: 'fruits-c4d50.firebasestorage.app',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFPOb4ViHYsCSYdahBLfD44wZ0WINt3js',
    appId: '1:1000135660682:ios:e155408f22e28718dc8973',
    messagingSenderId: '1000135660682',
    projectId: 'fruits-c4d50',
    storageBucket: 'fruits-c4d50.firebasestorage.app',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx12V7Sdsd73muCrmMW6Sq0_eQRAyZ9ic',
    appId: '1:1000135660682:web:6a281dc570d51541dc8973',
    messagingSenderId: '1000135660682',
    projectId: 'fruits-c4d50',
    authDomain: 'fruits-c4d50.firebaseapp.com',
    storageBucket: 'fruits-c4d50.firebasestorage.app',
    measurementId: 'G-W9P4ZHPMTJ',
  );
}
